#!/bin/sh -e
#
### BEGIN INIT INFO
# Provides:          nextdom-logic
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NextDom Logic Daemon
### END INIT INFO

set -e

test -f $DAEMON || exit 0

PID_FILE="/var/run/nextdom-logic.pid" 
DAEMON_START="/usr/bin/node"
DAEMON_OPTIONS="/usr/local/nextdom/logic/app.js"
DAEMON_USER="nextdom"
DAEMON_NAME="nextdom-logic"
 
. /lib/lsb/init-functions
 
process_start () {
  log_daemon_msg "Starting system $DAEMON_NAME Daemon"
  start-stop-daemon --background --oknodo --name $DAEMON_NAME --start --make-pidfile --pidfile $PID_FILE --quiet --chuid $DAEMON_USER --exec $DAEMON_START $DAEMON_OPTIONS
  log_end_msg $?
}
 
process_stop () {
  log_daemon_msg "Stopping system $DAEMON_NAME Daemon"
  start-stop-daemon --oknodo --pidfile $PID_FILE --stop --retry 5 --quiet
  log_end_msg $?
}
 
case "$1" in
  start|stop)
    process_${1}
    ;;
  restart|reload|force-reload)
    process_stop
    process_start
    ;;
  force-stop)
    process_stop
    killall -q $DAEMON_NAME || true
    sleep 2
    killall -q -9 $DAEMON_NAME || true
    ;;
  status)
    status_of_proc "$daemon_NAME" "$DAEMON" "system-wide $daemon_NAME" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$daemon_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
    exit 1
    ;;
  esac
exit 0
